// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod isotime {

    #[allow(unused_imports, dead_code)]
    pub mod storage {

        pub enum EntryOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct Entry<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for Entry<'a> {
            type Inner = Entry<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> Entry<'a> {
            pub const VT_KEY: ::flatbuffers::VOffsetT = 4;
            pub const VT_VALUE: ::flatbuffers::VOffsetT = 6;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                Entry { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args EntryArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<Entry<'bldr>> {
                let mut builder = EntryBuilder::new(_fbb);
                if let Some(x) = args.value {
                    builder.add_value(x);
                }
                if let Some(x) = args.key {
                    builder.add_key(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn key(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                            Entry::VT_KEY,
                            None,
                        )
                }
            }
            #[inline]
            pub fn value(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                            Entry::VT_VALUE,
                            None,
                        )
                }
            }
        }

        impl ::flatbuffers::Verifiable for Entry<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "key",
                        Self::VT_KEY,
                        false,
                    )?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "value",
                        Self::VT_VALUE,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct EntryArgs<'a> {
            pub key: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
            pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
        }
        impl<'a> Default for EntryArgs<'a> {
            #[inline]
            fn default() -> Self {
                EntryArgs {
                    key: None,
                    value: None,
                }
            }
        }

        pub struct EntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EntryBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_key(
                &mut self,
                key: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_
                    .push_slot_always::<::flatbuffers::WIPOffset<_>>(Entry::VT_KEY, key);
            }
            #[inline]
            pub fn add_value(
                &mut self,
                value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_
                    .push_slot_always::<::flatbuffers::WIPOffset<_>>(Entry::VT_VALUE, value);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> EntryBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                EntryBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<Entry<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for Entry<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("Entry");
                ds.field("key", &self.key());
                ds.field("value", &self.value());
                ds.finish()
            }
        }
        pub enum SSTableDataOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct SSTableData<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for SSTableData<'a> {
            type Inner = SSTableData<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> SSTableData<'a> {
            pub const VT_ENTRIES: ::flatbuffers::VOffsetT = 4;
            pub const VT_BLOOM_FILTER: ::flatbuffers::VOffsetT = 6;
            pub const VT_NUM_HASHES: ::flatbuffers::VOffsetT = 8;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                SSTableData { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args SSTableDataArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<SSTableData<'bldr>> {
                let mut builder = SSTableDataBuilder::new(_fbb);
                builder.add_num_hashes(args.num_hashes);
                if let Some(x) = args.bloom_filter {
                    builder.add_bloom_filter(x);
                }
                if let Some(x) = args.entries {
                    builder.add_entries(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn entries(
                &self,
            ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry<'a>>>>
            {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry>>,
                    >>(SSTableData::VT_ENTRIES, None)
                }
            }
            #[inline]
            pub fn bloom_filter(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                            SSTableData::VT_BLOOM_FILTER,
                            None,
                        )
                }
            }
            #[inline]
            pub fn num_hashes(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(SSTableData::VT_NUM_HASHES, Some(0))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for SSTableData<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Entry>>,
                    >>("entries", Self::VT_ENTRIES, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "bloom_filter",
                        Self::VT_BLOOM_FILTER,
                        false,
                    )?
                    .visit_field::<u32>("num_hashes", Self::VT_NUM_HASHES, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct SSTableDataArgs<'a> {
            pub entries: Option<
                ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry<'a>>>,
                >,
            >,
            pub bloom_filter: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
            pub num_hashes: u32,
        }
        impl<'a> Default for SSTableDataArgs<'a> {
            #[inline]
            fn default() -> Self {
                SSTableDataArgs {
                    entries: None,
                    bloom_filter: None,
                    num_hashes: 0,
                }
            }
        }

        pub struct SSTableDataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SSTableDataBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_entries(
                &mut self,
                entries: ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<Entry<'b>>>,
                >,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    SSTableData::VT_ENTRIES,
                    entries,
                );
            }
            #[inline]
            pub fn add_bloom_filter(
                &mut self,
                bloom_filter: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    SSTableData::VT_BLOOM_FILTER,
                    bloom_filter,
                );
            }
            #[inline]
            pub fn add_num_hashes(&mut self, num_hashes: u32) {
                self.fbb_
                    .push_slot::<u32>(SSTableData::VT_NUM_HASHES, num_hashes, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> SSTableDataBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                SSTableDataBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<SSTableData<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for SSTableData<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("SSTableData");
                ds.field("entries", &self.entries());
                ds.field("bloom_filter", &self.bloom_filter());
                ds.field("num_hashes", &self.num_hashes());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `SSTableData`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_sstable_data_unchecked`.
        pub fn root_as_sstable_data(
            buf: &[u8],
        ) -> Result<SSTableData<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<SSTableData>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `SSTableData` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_sstable_data_unchecked`.
        pub fn size_prefixed_root_as_sstable_data(
            buf: &[u8],
        ) -> Result<SSTableData<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<SSTableData>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `SSTableData` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_sstable_data_unchecked`.
        pub fn root_as_sstable_data_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<SSTableData<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<SSTableData<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `SSTableData` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_sstable_data_unchecked`.
        pub fn size_prefixed_root_as_sstable_data_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<SSTableData<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<SSTableData<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a SSTableData and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `SSTableData`.
        pub unsafe fn root_as_sstable_data_unchecked(buf: &[u8]) -> SSTableData<'_> {
            unsafe { ::flatbuffers::root_unchecked::<SSTableData>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed SSTableData and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `SSTableData`.
        pub unsafe fn size_prefixed_root_as_sstable_data_unchecked(buf: &[u8]) -> SSTableData<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<SSTableData>(buf) }
        }
        #[inline]
        pub fn finish_sstable_data_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<SSTableData<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_sstable_data_buffer<
            'a,
            'b,
            A: ::flatbuffers::Allocator + 'a,
        >(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<SSTableData<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    } // pub mod storage
} // pub mod isotime
